version: "2"

networks:
  workernet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "12.3.0.0/24"
          gateway: "12.3.0.1"
  default:
    driver: bridge

services:
  # db:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   env_file: .env
  #   networks:
  #     workernet:
  #       ipv4_address: 12.3.0.4
  #   volumes:
  #     - .:/usr/pinky/

  bot:
    container_name: pinky
    env_file: .env
    ports:
      - "8448:8448"
    image: node:erbium-alpine
    networks:
      workernet:
        ipv4_address: 12.3.0.5
    restart: always
    # depends_on:
    #   - db
    volumes:
      - .:/usr/pinky
      - /usr/pinky/node_modules
    working_dir: /usr/pinky
    command: yarn prod
