version: "2"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - .:/usr/pinky/

  bot:
    container_name: pinky
    env_file: .env
    ports:
      - "8448:8448"
    image: node:erbium-alpine
    restart: "always"
    depends_on:
      - db
    volumes:
      - .:/usr/pinky
      - /usr/pinky/node_modules
    working_dir: /usr/pinky
    command: yarn prod
