apiVersion: v1
kind: Deployment
metadata:
  name: pinky-bot
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: pinky
        resources:
          limits:
            cpu: 1
            memory: 2024
        image: devsamuelv/pinky-bot