# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          path: $GITHUB_WORKSPACE
      - uses: SpicyPizza/create-envfile@v1
        with:
          directory: $GITHUB_WORKSPACE
          envkey_TOKEN: ${{ secrets.TOKEN }}
          file_name: .env
      - run: docker-compose up -d
