name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.password }} | sudo -s
      - run: docker-compose kill
      - run: docker-compose up -d
