name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          envkey_TOKEN: ${{ secrets.TOKEN }}
          file_name: .env
      - run: echo ${{ secrets.password }} | sudo -S
      - run: docker-compose kill
        with:
          envkey_TOKEN: ${{ secrets.TOKEN }}
          file_name: .env
      - run: docker-compose up -d
