# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # echo ${{ secrets.password }} | sudo -S

    steps:
      - uses: actions/checkout@v2

      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_TOKEN: ${{ secrets.TOKEN }}
          # directory: <directory_name>
          file_name: .env

      - run: docker-compose up -d
      # NPM
      # - uses: actions/checkout@v2
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # Yarn
      # - uses: actions/checkout@v2
      # - uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: install
      # - uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: install
