name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    # env:
    #   TOKEN: ${{ secrets.TOKEN }}

    steps:
      - run: sudo -S chgrp -R samuel /home/deploy/actions-runner/working-dir/Pinky/Pinky/build | sudo chmod -R ug+rwX /home/deploy/actions-runner/working-dir/Pinky/Pinky/build | sudo find /home/deploy/actions-runner/working-dir/Pinky/Pinky/build -type d -exec chmod g+s {} +
      - uses: actions/checkout@v2
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TOKEN: ${{ secrets.TOKEN }}
          file_name: .env
      - run: docker-compose kill
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TOKEN: ${{ secrets.TOKEN }}
          file_name: .env
      - run: docker-compose up -d
