name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    # env:
    #   TOKEN: ${{ secrets.TOKEN }}

    steps:
      # if docker-compose up fails comment this then when it passes uncomment
      - run: echo ${{ secrets.PASSWORD }} | sudo -S chgrp -R samuel /home/deploy/actions-runner/working-dir/Pinky/Pinky | echo ${{ secrets.PASSWORD }} | sudo -S chmod -R ug+rwX /home/deploy/actions-runner/working-dir/Pinky/Pinky | echo ${{ secrets.PASSWORD }} | sudo -S find /home/deploy/actions-runner/working-dir/Pinky/Pinky -type d -exec chmod g+s {} +
      - uses: actions/checkout@v2
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TOKEN: ${{ secrets.TOKEN }}
          file_name: .env
      - run: echo ${{ secrets.PASSWORD }} | sudo -S docker-compose kill
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TOKEN: ${{ secrets.TOKEN }}
          file_name: .env
      - run: docker-compose up -d
