# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TOKEN: ${{ secrets.TOKEN }}
          file_name: .env
      - run: docker-compose kill
      - uses: actions/checkout@v2
          with: 
            path: "pinky"

      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TOKEN: ${{ secrets.TOKEN }}
          file_name: .env
      - run: docker-compose up -d
