name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -H 192.168.0.4:2375 up -d
